"""Custom validators."""

from django.core.exceptions import ValidationError


def items_validator():
    pass

